### PR TITLE
Implemented tvOS framework.

### PR DESCRIPTION
**Pull request by Baza207**
Created a tvOS Framework.

Possibly already in progress, but I needed it for using some of my projects I'm working on for the Apple TV, so I thought I'd share.

I've run the iOS unit tests on the target and that all pass. However the CacheTestCase tests randomly fail for no reason on some occasions. Normally a max of 3 out of the 5 fail, but normally just one of them does (but not always the same one). I'm not sure if this is an Xcode beta thing or that the tests were designed for iOS not tvOS.

### CODE REVIEW

**Comment by jmkr** [comment]
For anyone else trying to get this working with Cocoapods, had to add `s.tvos.deployment_target = '9.0'` to the podspec.

And incase you'd like some Gemfile cliffnotes for tvOS support in Cocoapods: :ok_hand: 

```
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'tvos'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :branch => 'tvos-support'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :branch => 'tvos-support'
```

**Comment by Baza207** [comment]
Thanks for that. I'll force push an update including that tomorrow.

**Comment by cnoon** [comment]
Thanks for your PR @Baza207...much appreciated! I ended up merging a modified version of #767. Thanks again!

**Comment by Baza207** [comment]
No worries. Glad I could help.

**Comment by loretoparisi** [comment]
It's not directly related to this, anyway I'm getting the same error on XCode 7.1 / tvOS 9.0 (13T5347l) and AppleTV DevelopmentKit:

dyld: Library not loaded: @rpath/ObjectiveLyricsTouchTV.framework/ObjectiveLyricsTouchTV
  Referenced from: /var/mobile/Containers/Bundle/Application/DD87E506-BA2A-47E6-8772-CEE7E1B57FD4/AppTestbedTV.app/AppTestbedTV
  Reason: image not found

**Comment by Baza207** [comment]
That sounds to me like you haven't actually added the framework "ObjectiveLyricsTouchTV.framework" to your target. Nothing specifically related to Alamofire.

Check your "Build Phases" and then "Embedded Binaries". Might be you need to add that framework there.

**Comment by loretoparisi** [comment]
Thank you,  sorry it was not directly related to Alamofire but not so docs about The AppleTVDevKit so far! I will check it out.

**Comment by loretoparisi** [comment]
@Baza207 If can help someone in the future I get it working putting the framework in both "Linked Frameworks and Libraries" and "Embedded Binaries".

**Comment by Baza207** [comment]
@loretoparisi I would move this to [StackOverflow](http://stackoverflow.com), as that's the better place to ask this type of question. Issues in GitHub projects are more for issues or bugs with the respective repo only.

I'm in SO with the same username if you want to try and @ me.

**Pull request closed without merging**
