### PR TITLE
Ss18/pr0

### PR DESCRIPTION
**Pull request by ss18**
### Goals :soccer:
Fixed typos in code and comments:
aquiring -> acquiring
didnt -> didn't
occured -> occurred
reponse -> response
recieves -> receives
recieve -> receive

### Testing Details :mag:
No testing needed.

Found with: https://github.com/ss18/grep-typos

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! However, our documentation is automatically generated, and so should not be touched by this PR. Can you limit the changes to just `.swift` files? We'll update the HTML docs when we do a new release.

**Comment by ss18** [comment]
@jshier Done. However, I did not revert changelog.md please let me know should I revert it?

**Comment by jshier** [comment]
@ss18 We just merged a major API documentation update. It would be great if you could rerun this tool and update the PR to fix any remaining typos. Still no need for the HTML. Thanks!

**Comment by ss18** [comment]
@jshier Done!

**Comment by jshier** [comment]
Looks good, thanks!

**Pull request merged**
