### PR TITLE
Docummentation status response example

### PR DESCRIPTION
**Pull request by saulurias**
### Goals :soccer:
Provide developers an example of how to obtain the http status code from the response.

### Implementation Details :construction:
Took me a while to find the http code so I decided that could be good to have it on the Response Handling docummentation example.

### Testing Details :mag:
Not needed

### CODE REVIEW

**Comment by jshier** [comment]
Sorry, you're still pointing to the `alamofire5` branch from your forked repo. On your fork, checkout `master`, pull to make sure you're up to date with our `master`, then create your branch. Apply your change to that branch and then create your PR. When that's done, the only change you should see for the PR is what you added, with the number of changed files being 1.

**Comment by saulurias** [comment]
That's exactly what I have been doing 🤔

**Comment by jshier** [comment]
You local branch is from our `alamofire5` branch, which is why you see all of our AF5 changes in your list of commits.

**Comment by saulurias** [comment]
oh I see, thanks I will check it again.

**Pull request closed without merging**
