### PR TITLE
Update podspec to 4.0.0, update deployment targets.

### PR DESCRIPTION
**Pull request by jshier**
Updates the podspec to version 4.0.0 and sets the deployment targets to match the project’s new deployment targets.

Also fixes a build issue with the iOS Example app.

### CODE REVIEW

**Comment by cnoon** [comment]
Looks good to me @jshier.

**Comment by rs10693** [comment]
Hello @cnoon,

I am using Alamofire but right now i am facing issue on swift 3. so please help me. Here i am adding my pod file text and also error.

My Deployment target is 8.0 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'project' do

pod 'Alamofire', '~> 4.0'

end
If i am wrong then suggest me.
error

**Comment by cnoon** [comment]
You cannot use Alamofire 4 with a deployment target of iOS 8.0 @rs10693.

**Comment by rs10693** [comment]
so i want  to use alamofire library in deployment target 8.0 and also use in swift 3, so plz suggest better option. @cnoon

**Pull request merged**
