### PR TITLE
Resolving Swift 3 errors (Xcode 8 Beta compatibility)

### PR DESCRIPTION
**Pull request by CodeBenson**
Did resolve swift 3 errors

### CODE REVIEW

**Comment by CodeBenson** [comment]
The project builds using Xcode 8 Beta, all tests passed. But Travis doesn't like it because he is using Xcode 7.3

**Comment by jshier** [comment]
There are already active `swift3` and `swift2.3` branches.

**Comment by CodeBenson** [comment]
I know that there is a branch for swift3, but it doesn't compile with Xcode 8 beta and I needed to fix that for my project anyway. That was the first time I tried to contribute to a project. Maybe forking was the right choice?

**Comment by jshier** [comment]
The branch certainly does compile with Xcode 8, as there is no other way to update to Swift 3. Have you updated to Xcode 8 beta 2?

**Comment by CodeBenson** [comment]
Indeed I missed the update, thank you!

**Pull request closed without merging**
