### PR TITLE
update iOS Example

### PR DESCRIPTION
**Pull request by rain2540**

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! However, this doesn't seem to refactor anything, it just adds whitespace. What value does this add?

**Comment by rain2540** [comment]
@jshier  There are the other changes
[No.1 - remove a unused property](https://github.com/Alamofire/Alamofire/pull/3268/commits/dafa8d7cb8f9357cceda8366c72e9f6a7f57d536)
[No.2 - indexPath: NSIndexPath -> indexPath: IndexPath](https://github.com/Alamofire/Alamofire/pull/3268/commits/799891db21b71b324ae83ddf8ab0e8d5098cb6b4)

**Comment by jshier** [comment]
@rain2540 Those changes, without the whitespace changes, would be fine. If you can update the PR with only those changes we can merge it.

**Comment by rain2540** [comment]
@jshier  I've deleted the whitespace changes

**Comment by rain2540** [comment]
@jshier I've remove the storyboard changes.

**Pull request merged**
