### PR TITLE
Switch test suite to use Given | When | Then structure

### PR DESCRIPTION
**Pull request by cnoon**
This PR contains several major changes to the test suite including:

1. Refactors all tests to follow the `Given` | `When` | `Then` structure
1. All tests now succeed on iOS and OS X
1. Adds safeguards to all tests to prevent the test suite from crashing when tests fail

My apologies for the horrendous diff. I would suggest checking out the branch and reviewing it that way. None of the tests have been removed. They have only been refactored to follow the new structure and to be safe from potential crashes.

### CODE REVIEW

**Comment by cnoon** [comment]
cc @kcharwood, @mattt and @kylef for review.

**Comment by kcharwood** [comment]
What do we need to do to get Travis or some other CI setup here?

**Comment by cnoon** [comment]
We need Travis CI to support Xcode 6.3 because we've moved over to Swift 1.2 which only ships in that version of Xcode.

**Comment by mattt** [comment]
I dig it. Nice work, @cnoon.

**Comment by kylef** [comment]
:+1:

**Pull request merged**
