### PR TITLE
Fix issues as of Xcode 6.3b2

### PR DESCRIPTION
**Pull request by rastersize**
:tada: 

#353 should also be merged for the example project to build fully (didn’t want to duplicate those changes in this PR).

Travis will fail given the requirements for the xcode-6.3 branch.

### CODE REVIEW

**Comment by jonah-williams** [comment]
I would find this change useful. I would be great to have it merged into the `Xcode-6.3` branch.

**Comment by stevestreza** [comment]
This change fixed my build in Xcode 6.3 beta 2.

**Comment by mattt** [comment]
Thanks so much, @rastersize. This is merged with 2f39b86.

**Comment by stevestreza** [comment]
Thank you @rasterize and @mattt!

**Comment by jonah-williams** [comment]
Much appreciated, thanks for including this. I'm back on the `xcode-6.3` branch and running happily again.

**Pull request closed without merging**
