### PR TITLE
Update Alamofire to Swift 2.2 (including test project)

### PR DESCRIPTION
**Pull request by nickskull**
Updated to fix warnings related to Swift 2.2 in Manager and ResponseSerialization. Also fixed one warning in the example project.

[There was one catch](https://github.com/nickskull/Alamofire/blob/680c1fad020fe0eeb541a99d9415774fa374a00d/Source/Manager.swift#L680) however for OS X version, where I had to take a switch `case` out of the switch and make it an `if`.

If you have any other idea how to improve, I will gladly change the implementation.

### CODE REVIEW

**Comment by cnoon** [comment]
Thanks @nickskull, we're hoping to get these fixes incorporated into Alamofire today and a release cut.

**Comment by nickskull** [comment]
@cnoon Great, thanks! If you need any more changes done or something updated let me know. 

Also, I tried to get Travis to work but it somehow fails every time and I am not quite sure what is the issue. I ran all tests for all platforms on my computer and everything passed without any problems, so can't see why is Travis complaining.

**Comment by Trhacz** [comment]
@nickskull  I am getting warning for Alamofire/Source/ParameterEncoding.swift  247:29: 'init(start:end:)' is deprecated: it will be removed in Swift 3.  Use the '..<' operator.

Are you going to change it as well?

**Comment by nickskull** [comment]
@Trhacz That was already fixed on the swift_2.2 branch by @Baza207 :)

**Comment by danielrhodes** [comment]
For some reason, Alamofire is not compiling for x86_64 (but does for the simulator)

**Comment by nickskull** [comment]
@danielrhodes I can't reproduce your issue. Are you using the newest Xcode version? Also what does it complain about?

**Comment by tosbaha** [comment]
I think there is also one more fix for Swift 2.2 

Manager.swift
===
```swift
   public func URLSession(
            session: NSURLSession,
            task: NSURLSessionTask,
            didReceiveChallenge challenge: NSURLAuthenticationChallenge,
            completionHandler: ((NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Void))
        {


            if let taskDidReceiveChallenge = taskDidReceiveChallenge {
                completionHandler(taskDidReceiveChallenge(session, task, challenge))
```
gives 

> Passing 2 arguments to a callee as a single tuple value is deprecated

I fixed by manually creating the tuple.

```swift
                let (disposition,credential) = taskDidReceiveChallenge(session, task, challenge)
                completionHandler(disposition,credential)
```

The reason is stated in [here](https://github.com/apple/swift/blob/master/test/Misc/misc_diagnostics.swift#L139)

**Comment by nickskull** [comment]
@tosbaha That is fixed in my commit.

**Comment by danielrhodes** [comment]
@nickskull I'm going to create a fresh project and get back to you

**Comment by danielrhodes** [comment]
Ok created a fresh project and it seems to work fine. I'm totally confused then what that issue is. :-P

**Comment by cnoon** [comment]
Thanks for putting this together @nickskull...much appreciated! I made some slight variations to your changes and pushed them up in 38606315 while still giving you attribution. I made some other modifications in 22c81a3b to the Travis yaml file. I still don't have all the Travis problems worked out, but everything is looking good locally across all platforms.

Thanks again! 🍻

> These changes will be released shortly...

**Comment by nickskull** [comment]
@cnoon Thanks, will update all my projects then! :beers:

**Pull request closed without merging**
