### PR TITLE
Target for watchOS 2 added

### PR DESCRIPTION
**Pull request by tomco**

### CODE REVIEW

**Comment by cnoon** [comment]
Nice...thanks for this @tomco. I have a few other things that I'm working on completing in Alamofire at the moment but I'll get to this as soon as possible!

**Comment by jurvis** [comment]
@tomco think you should also check the "Shared" checkbox in the watchOS scheme, else Carthage will not be able to discover the scheme when running `carthage update`

**Comment by tomco** [comment]
@jurvis thx missed that. Fixed now.

**Comment by cnoon** [comment]
Thank you for all your hard work here @tomco! I squashed your PR, tweaked it slightly and pushed it into the `swift-2.0` branch in b4cb7cc3 giving you attribution. Great work!

Cheers 🍻

**Pull request closed without merging**
