### PR TITLE
Add description for SPM API version 4

### PR DESCRIPTION
**Pull request by hayashikun**
### Goals :soccer:
Enable to build project including Alamofire by using Swift Package Manager API Version 4

### Implementation Details :construction:
Recently, Swift Package Manager API Version is updated.
So, I added how to write `Package.swift` in APIv4 format.

https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md
https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! I think it would be less confusing to just mark the two sections as Swift 3.1 and Swift 3.2+ or perhaps Xcode 8 and Xcode 9. Once that change is made it can be merged.

**Comment by hayashikun** [comment]
Actually, API version is not compatible with Swift version or Xcode version. 
So, marking `Swift tools version 3, 4` is correct, I think.

The default tools version is same with swift major version.
So there is a option to mark Swift 3 and Swift 4.

Which is the best?

**Comment by jshier** [comment]
Version 3 shipped with the Swift 3 compiler and version 4 with the Swift 4 compiler, no? That should match exactly to Xcode versions, so that's probably the simplest way to indicate the distinction.

**Comment by hayashikun** [comment]
https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md#swiftlanguageversions

We can use APIv3 from Swift 4, but it is rare case. So I marked `Swift 3` and `Swift 4`

**Comment by jshier** [comment]
How would you invoke the v3 behavior in the Swift 4 compiler? By having a `Package.swift` with a `swiftLanguageVersions` of `[3]`?

**Comment by hayashikun** [comment]
In swift 4 compiler, default tool verion is 4 just after `swift package init`.
I can change swift tool version 3 by typing `swift package tools-version --set 3.0.0`

**Comment by hayashikun** [comment]
or
Top line of `Package.swift` default is `// swift-tools-version:4.0`.
By changing this to `// swift-tools-version:3.0`, swift package tool version is switched.

**Comment by jshier** [comment]
Thanks! Cheers! :beers:

**Pull request merged**
