### PR TITLE
Reorganize the README.md file

### PR DESCRIPTION
**Pull request by pateljay43**
### Issue Link :link: 
- [#2223](https://github.com/Alamofire/Alamofire/issues/2223)

### Goals :soccer:
- Reorganize the README.

### Implementation Details :construction:
- Separated Usage & Advanced Usage sections into individual markdown files.

### CODE REVIEW

**Comment by pateljay43** [comment]
@jshier Hope this is what you expected from #2223

**Comment by jshier** [comment]
@pateljay43 Thanks for your work so far! I was actually envisioning something more complete, where each section of the README is moved into their own file, but all of the section links, and details, link out to those files.

**Comment by pateljay43** [comment]
@jshier Just to confirm - all sections are to be moved or just the sections after the 'Installation'?

**Comment by jshier** [comment]
Just the stuff after installation. And I'd like to keep the links up top (the detailed links for advanced usage, for example) intact. Thanks!

**Comment by pateljay43** [comment]
I think this is what @jshier expected

**Comment by jshier** [comment]
@pateljay43 Sorry this has taken so long, we were discussing whether to move to wiki. We don't think it's necessary, but I we do have some final changes for your PR.

When I mentioned making sure the section links still worked, I meant to just make sure to keep all of the links at the top of the `README` in place and working. Those links don't need to be added to all of the other files. Aside from that, make sure the links between the subfiles are still working and it should be good to go.

Thanks for your work here!

**Comment by jshier** [comment]
Sorry, @pateljay43, but I've merged an initial separation to get this refactor done. We'll be looking at further refactors in the futures. Thanks for the work!

**Pull request closed without merging**
