### PR TITLE
Fixing NSNumber vs Bool type issue.

### PR DESCRIPTION
**Pull request by dhanushram**
Proposed fix for https://github.com/Alamofire/Alamofire/issues/1458

### CODE REVIEW

**Comment by cnoon** [comment]
Thanks for the PR @dhanushram, but we won't be accepting this change for the same reasons we rejected it in #1056.

Thanks anyways. Cheers. 🍻

**Comment by cnoon** [comment]
My apologies here @dhanushram...I completely misunderstood what you were doing. Too many late nights. I'm going to re-open and investigate further.

**Comment by jshier** [comment]
This seems like what Argo had to deal with in properly detecting `Bool` from `JSONSerialization`. Their solution was to [drop down to CoreFoundation](https://github.com/thoughtbot/Argo/blob/841979f8b8341b7818a15e67662157c4580151f1/Argo/Extensions/NSNumber.swift) and use those APIs to properly detect that an `NSNumber` contained a `Bool`. I think that's the solution we need here. If we can cast to a a `Bool` then check if it's an `NSNumber`. If it isn't we're good, it's a `Bool`. Otherwise check to see if the `NSNumber` contains a `Bool`.

**Comment by cnoon** [comment]
Thanks for putting this together @dhanushram...much appreciated! @jshier is certainly right and it required a more robust check. We had to do something similar in Elevate. I've implemented a `fileprivate` NSNumber extension in the `ParameterEncoding.swift` file and leveraged it in the `queryComponents` API. I've also added failing (now passing) unit tests. I pushed up the fix to `master` in 72958d0e.

Thanks again! 🍻

**Pull request closed without merging**
