### PR TITLE
Podspec

### PR DESCRIPTION
**Pull request by mrackwitz**
I used your framework and it's app target as Example project in the pull-request CocoaPods/CocoaPods#2835, which will bring Swift support to CocoaPods. See [here](https://github.com/CocoaPods/CocoaPods/tree/swift/examples/Alamofire%20Example). I hope this okay for you. I'd love to see it published in the master spec repo.

### CODE REVIEW

**Comment by mattt** [comment]
@kylef Sounds good. Thanks, @mrackwitz for the PR. I'm really happy to do what I can to help drive CocoaPods adoption for Swift. This is going to be a huge improvement to how folks get started with Alamofire; I can't thank y'all enough for all of your hard work to make this possible.

**Comment by iasandcb** [comment]
The merged podspec seems out of date, particularly, 

  s.version = '1.1.0' -> '1.1.3'
  s.source = { :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '1.1.0' } -> '1.1.3'

  s.ios.deployment_target = '8.0' -> '7.0'

Thanks in advance for the update above.

**Comment by thedamfr** [comment]
Hum... Something is weird.
when I add Alamofire my Bridging header breaks. Older dependencies which where Objective-C bridged to Swift can't be imported anymore.
I'm using 0.36.0.beta.1

**Comment by segiddins** [comment]
@mattt do you have a timeline on submitting the spec to trunk?

**Comment by JustinDSN** [comment]
@thedamfr after upgrading to Cocoapods 0.36.0.beta.1, adding ```pod 'Alamofire', '~> 1.1.3'``` to my existing pod file that contains:

```
target 'MyApp', :exclusive => true do
  pod 'AFNetworking', '~> 2.5'
  pod 'ProtocolBuffers', '1.9.3'
  pod 'KSDeferred', '~> 0.2'
  pod 'Rollbar', '~> 0.1.2'
  pod 'Alamofire', '~> 1.1.3'
end
```

I receive the error **failed to import bridging header** and an error of **'AFNetworking.h' file not found'** on the line ```#import "AFNetworking.h"``` in the bridging header.

**Comment by segiddins** [comment]
@JustinDSN try changing that to either `@import AFNetworking;" or `#import <AFNetworking/AFNetworking.h>`.

**Comment by thedamfr** [comment]
@JustinDSN just remove the bridging header.
and user import AFNetworking in you swift file. 
It's the way it works.

**Pull request merged**
