### PR TITLE
Add change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags in your repo.

For such cases I create a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** from :octocat: Issue Tracker.

This PR add change log file to your repo (generated by this script).
You can check, how it is look like here: [Change Log](https://github.com/skywinder/Alamofire/blob/add-change-log-file/CHANGELOG.md)

Some essential features, that has this script:

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )
- Distinguish issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)
- Generate neat Change Log file according basic [change log guidelines](http://keepachangelog.com).

You can easily update this file in future by simply run script: `github_changelog_generator Alamofire/Alamofire` in your repo folder and it make your Change Log file up-to-date again!

Hope you find this commit as useful. :wink:

### CODE REVIEW

**Comment by cnoon** [comment]
Hi @skywinder, thank you for your pull request. Your generator seems very powerful, but we're still discussing how we'd like to format our CHANGELOG. We'll keep you posted 👍🏻

**Comment by skywinder** [comment]
Thanks! Let me know, if you have any suggestions, how to improve it!

**Comment by cnoon** [comment]
We have completed our initial CHANGELOG in 34224b01. Thank you again for your pull request, but we've decided to roll our own manual solution for now to provide the highest quality info we can. Thanks again 🍻

**Comment by skywinder** [comment]
Very nice format. Of course it much better, than auto-changed log! Great work! :+1: 

bdw: I'm going to add feature like partial updates https://github.com/skywinder/github-changelog-generator/issues/209 probably then you can use this tool to generate a nice stub for new releases. Cheers! :beers:

**Pull request closed without merging**
