### PR TITLE
Make `HTTPMethod` Sendable

### PR DESCRIPTION
**Pull request by bestwnh**
### Goals :soccer:
Just like the https://github.com/Alamofire/Alamofire/pull/3816 but for `HTTPMethod`.
image

### CODE REVIEW

**Comment by jshier** [comment]
Thanks. I'll audit the other simple types.

**Comment by bestwnh** [comment]
@jshier Maybe it's time to begin the process to fully support concurrency? 👀

**Comment by jshier** [comment]
Full support is impossible until Apple's frameworks themselves fully support it, but Alamofire is generally thread-safe, even if it can't always provide `Sendable` conformances. For the most part I can add `Sendable` support to Alamofire's simple types, and I already declare such support as `@unchecked` for the `Request` types (which are manually thread-safe through locks and controlled queue usage), but complex types like `AFError` can't truly be `Sendable` until the various system types it captures are themselves `Sendable`. In the meantime, an audit of the simple public types should be possible.

**Review by jshier — APPROVED** [review]

**Comment by bestwnh** [comment]
Thanks for your explanation. I used to think that only UIKit is lack of concurrency support. Alamofire only use Foundation so I though it would be easier. I believe Alamofire is thread-safe. But I still want to kill all warning.

**Comment by jshier** [comment]
Sure. Feel free to report any others but remember, you can use `@preconcurrency import Alamofire` to silence them in general.

**Pull request merged**
