### PR TITLE
Fix Xcode 8.1 Warnings

### PR DESCRIPTION
**Pull request by jshier**
This PR fixes the one new warning in Xcode 8.1 that was due to the new handling of optionals implicitly cast as `Any`. It also adopts the new project settings suggested by Xcode.

### CODE REVIEW

**Comment by RafaelPlantard** [comment]
@jshier did occur a build fail.

**Comment by cnoon** [comment]
This looks @jshier! 🍻

**Comment by Harmonium** [comment]
I still have the warnings after updated to v4.2.0

**Comment by cnoon** [comment]
There aren't warnings in the project anymore. You must have something else going on. Possibly clean and wipe derived data?

**Comment by Harmonium** [comment]
I did it before writing the comment! I reinstalled the pods too to be sure.

**Comment by cnoon** [comment]
What are you seeing as an error @Harmonium?

**Comment by Harmonium** [comment]
These are the warnings I have:

Expression implicitly coerced from 'URLRequest?' to Any
Expression implicitly coerced from 'Data?' to Any

**Comment by cnoon** [comment]
Screenshot? What version of Xcode are you running? We only support Xcode 8.1 currently. If you're running a beta that is producing those errors, then that's the problem.

**Comment by Harmonium** [comment]
Is this what you wanted?

**Comment by Harmonium** [comment]
So, no ideas of what is going on? ;-)

**Comment by jshier** [comment]
There are no warnings using Xcode 8.1 and the latest Alamofire release. If you see any new ones, please open a new issue with the exact warnings you're seeing and the lines in Alamofire that trigger them

**Comment by Harmonium** [comment]
Maybe you can help here.

                switch response.result {
                    
                case .success:
                    
                case .failure(let error):
                    print(response.request)
                    print(response.data)
                }

I have the warnings at these 2 lines (print). Maybe I’m doing something wrong here. Is it the good way to do it?

Thanks for your help!

FG

**Comment by jshier** [comment]
Cast them as `Any` and be done with it or put them into string values that are then printed.

**Comment by Harmonium** [comment]
Thanks!

**Pull request merged**
