### PR TITLE
feat (Response) : update debugDescription

### PR DESCRIPTION
**Pull request by rain2540**
add parameters info for debugDescription of DataResponse and DownloadResponse

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! It's unlikely we'll be doing another release of Alamofire 4, but I'll keep this PR around until 5 is fully released.

**Comment by jshier** [comment]
@rain2540 Looks like we'll be doing a 4.9.1 release after all. If you can update your PR to use the `debugDescription` implementation from Alamofire 5, which includes the body data, we can make this PR part of that release.

**Comment by rain2540** [comment]
I've updated my PR to use the debugDescription implementation from Alamofire 5, which includes the body data.

**Comment by jshier** [comment]
Turns out your changes are incompatible with Alamofire 4. Please resubmit your PR with a building version. You can use the Alamofire 5 implementation as an example, but you can't copy the code directly.

**Comment by rain2540** [comment]
@jshier I've resubmitted my PR #2976

**Pull request merged**
