### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by jshier**
### Goals :soccer:
This PR fixes several memory leaks, mostly around `DataStreamRequest` (😬) and within our test suite.

### Implementation Details :construction:
Fixes were accomplished using `unowned` captures to ensure there are no memory cycles. Our tests had cycles due to strong captures in `ClosureEventMonitor` closures to requests or `Session`s.

### Testing Details :mag:
No new specific tests, but I did add a standalone test case, `LeaksTests`, that has a single method which registers an `atexit` handler which runs the leaks tool. This allows for semi-automated leaks testing using SPM. Just call `swift test -c debug -Xswiftc -DLEAKS` in the Alamofire directory and it will run the test suite (or as much of it as it can using SPM) and then run the `leaks` tool afterward, printing any leaks. The memory debugger in Xcode can also be used to find leaks.

### CODE REVIEW

**Comment by DenTelezhkin** [comment]
@jshier Apologies for out-of-nowhere question, but how are you able to run this leaks testing?

In my environment(Xcode 11.5, Mac OS Catalina 10.15.4) running `swift test -c debug -Xswiftc -DLEAKS` in Alamofire directory eventually crashes leaks command line tool with following crashlog: https://pastebin.com/Qza7y4Qv

**Comment by jshier** [comment]
@DenTelezhkin The `libswiftRemoteMirror42.dylib` in your crash log seems suspicious, you may want to double check the version of the command line tools you have installed and the version of Xcode you have selected for command line use.

**Comment by DenTelezhkin** [comment]
This truly was suspicious, but I have only one Xcode installed, and correct version of command lines tools(11.5, the only present) is selected. 

The mentioned `libswiftRemoteMirror42.dylib` file, along with `libswiftRemoteMirror.dylib` and `libswiftRemoteMirrorLegacy.dylib` are not even a part of Xcode, but rather part of Mac OS Catalina install - they reside in `/usr/lib/swift` even if you don't have Xcode installed.

Are you running those commands on Mac OS Catalina yourself?

**Comment by jshier** [comment]
Yes, it works fine. Can you run `leaks` at all?

**Comment by DenTelezhkin** [comment]
Yep, it sure does, running on my app written in SwiftUI:

```
> leaks 98795
Process:         Redacted [98795]
Path:            /Users/USER/Library/Developer/Xcode/DerivedData/Redacted-eohepbsmfjzzprdjbskucteuqsys/Build/Products/Debug-maccatalyst/Redacted.app/Contents/MacOS/Redacted
Load Address:    0x100000000
Identifier:      com.Redacted.Redacted
Version:         1.0 (2020.05.22.1004)
Code Type:       X86-64
Parent Process:  debugserver [98796]

Date/Time:       2020-05-28 11:15:36.696 +0300
Launch Time:     2020-05-28 11:14:34.023 +0300
OS Version:      Mac OS X 10.15.4 (19E287)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 11.5 (11E608c)

Physical footprint:         39.4M
Physical footprint (peak):  39.8M
----

leaks Report Version: 4.0
Process 98795: 85126 nodes malloced for 10968 KB
Process 98795: 0 leaks for 0 total leaked bytes.
```

**Pull request merged**
