### PR TITLE
chore: fix some typos

### PR DESCRIPTION
**Pull request by Sajjon**
### Goals :soccer:
Fix some typos.

### Testing Details :mag:
Installed firewalk, started it and ran `swift test` - tests passing.

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for these! This all looks good, but you can remove the changes to the docs files, those are generated from the inline docs in the code, so they'll update with the fixes when I do another release.

**Comment by Sajjon** [comment]
@jshier Here are some context:

I informed lots of repos that Github user "vivoxfold3" had suspicous activity:
1. has no sources (only forks)
2. no profile photo
3. no followers
4. no bio
5. forks ~10 crypto libs or repos used by crypto libs / wallets all *within the same hour*
6. makes trivial contributions and **tries to "falsify" a GPG signature** by writing "Signed off by"
7. ignores PR templates

The **exact same behaviour** was done by GH use `vivoxfold3` also last week, which responded using... hmm... interesting phrasing:

https://github.com/hoprnet/hoprnet/pull/6482#issuecomment-2333638612

> "Unreasonable accusations from persecuted delusional patients"

Whatever that means? Obvious bad translation service.

==================

The difference between you vivoxfold3 and me is that I:
1. Have many of SOURCE repos (not forks) with many stars
2. My Github User is over 10 years old
3. I have profile photo
4. I have 100 followers
5. I have a bio
6. I have many verified email addresses
7. I'm a Github PRO user
8. I do in fact work in the crypto industry, unlike you doing trivial PRs intro 10 different crypto libs...
9. My contributions fixing typos are non-trivial - often spent 1-3 hours per

**Comment by jshier** [comment]
Yeah, it was rather strange, especially since I'm pretty sure you've made PRs here before. Thanks.

**Comment by jshier** [comment]
I'll go ahead and merge, but the Jazzy and doc updates will simply be overwritten when I update the docs next.

**Pull request merged**
