### PR TITLE
Fix for Swift 2. Though there are two places I didn't fix.

### PR DESCRIPTION
**Pull request by NicholasTD07**
Search TODO in the project you will see those two places. Help wanted. :)

I think it's better to create a separate `swift-2` branch in `Alamofire/Alamofire` repo. This way it wouldn't mess up for people who is still using Swift 1.2 and `Carthage` when they do a `carthage update`. If they really want to use Swift 2 they can let Carthage follow `swift-2` branch in the config file `Cartfile`.

### CODE REVIEW

**Comment by NicholasTD07** [comment]
This is my first time contribute to Alamofire. If there's anything not right, please let me know, happy to change. :)

**Comment by rpowelll** [comment]
I'll take a look. It seems to be a combination of not handling potential errors thrown by `NSPropertyListSerialization.propertyListWithData(format:)` and some type inference issues.

**Comment by rpowelll** [comment]
So this fixes the first example, but it's _far_ from ideal:

```swift
do {
    if let
        HTTPBody = URLRequest.HTTPBody,
        _plist: AnyObject = try NSPropertyListSerialization.propertyListWithData(HTTPBody, options: .Immutable, format: nil),
        plist = _plist as? NSObject
    {
        XCTAssertEqual(plist, parameters as NSObject, "HTTPBody plist does not equal parameters")
    } else {
        XCTFail("plist should not be nil")
    }
} catch {
    XCTFail("Unable to load plist")
}
```

I'll look in to finding a way to express this code better.

**Comment by NicholasTD07** [comment]
@rpowelll Thank you!

Oh, by the way, I don't think Travis CI support Swift 2 yet. That's why it's failing. I have run all the tests and they pass, well, except those two todos which are commented out.

**Comment by rpowelll** [comment]
Yep, I'm not sure what Travis's stance on testing prerelease iOS SDKs is. Does anyone have experience with that?

**Comment by nickvelloff** [comment]
I do. Travis will allow user individually to test beta SDKs but generally they are out of prerelease before even a test environment is available. support@travis-ci.com the team there is super responsive and helpful.

**Comment by cnoon** [comment]
This is a great start @NicholasTD07! Thank you for putting this together. 

I'm going to dig into this tonight. I'll most likely pull in your changes and rework some of the error handling along with a few other minor things. I'll also most likely blacklist the `swift-2.0` branch from the Travis-CI yaml file until Travis supports the Xcode 7 beta.

Thanks again!

**Comment by NicholasTD07** [comment]
@cnoon My pleasure.

However I have to mention that because I wanted to get it to compile as fast as possible last night, some changes I made are a bit dodgy. But I think my pr would be a good starting point to get Alamofire to Swift 2.  So you don't need to fix all those tedious minor changes again. :)

**Comment by cnoon** [comment]
Thanks again for your work on this @NicholasTD07. 

I ended up starting from scratch given the small but challenging complexities that were presented in some of the changes. There were a few API changes introduced in iOS 9 along with some different external parameter naming conventions that I had to go through individually. It was also a bit interesting migrating over to the new error handling logic both in Alamofire and the test targets.

Everything has been completed and Travis-CI has been disabled in the new `swift-2.0` branch. I really wish that we could run Travis-CI over this branch with all the different simulators, but it isn't supported yet and probably won't be for at least a month. If everyone in the community could try this out I'd really appreciate it. All the tests are passing on both iOS 9 and Mac OS X 10.10. I'm having trouble with my iOS 8 simulators and don't have another install of Mac OS X 10.11 to test with.

Thanks again everyone for your help on this!

**Comment by rpowelll** [comment]
I'm working on a bunch of little projects to learn the new APIs in iOS 9, so I'll be sure to use Alamofire quite a bit in the coming months. Hopefully that'll help sort out any bugs before the Xcode 7 GM gets released.

**Comment by abunur** [comment]
anyone know how to properly update this Alamofire snippet using Swift 2.0 branch:


let JSONSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
let (JSON: AnyObject?, serializationError) = JSONSerializer(request, response, data)


The second line is throwing two errors in Xcode 7.0,

so in Xcode 7 it wants to change this


the error it shows is twofold,
1) expected a ‘,’ separator,

it wants to put a comma between AnyObject and ?

2) expected a pattern



Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
214.279.1890 (f)
twitter: @flexRonin
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: http://500px.com/fuad2

**Comment by cnbuff410** [comment]
Hi @cnoon, is there any way to specify in podfile that I want to use the Swift2.0 branch instead of master? Or whatelse way would you recommend to use Aamofire managed by CocoaPads in the Swift 2.0 project?

**Comment by abunur** [comment]
yes, it’s documented on the CocoaPods site:

https://guides.cocoapods.org/using/the-podfile.html <https://guides.cocoapods.org/using/the-podfile.html>

so in your podfile, use:

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
214.279.1890 (f)
twitter: @flexRonin
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: http://500px.com/fuad2

**Comment by abunur** [comment]
never mind, figured this one out.

AnyObject? is not required explicitly

so changing to this, compiles:

            let JSONSerializer = Request.JSONResponseSerializer(options: [.AllowFragments])
            let (JSON, serializationError) = JSONSerializer(request, response, data)


Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
214.279.1890 (f)
twitter: @flexRonin
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: http://500px.com/fuad2

**Comment by NicholasTD07** [comment]
I am using Carthage made by github team to manage my dependencies including Swift 2 ones. https://github.com/Carthage/Carthage



—

**Comment by cnbuff410** [comment]
Thanks abunur

**Pull request closed without merging**
