### PR TITLE
Add missing @discardableResult

### PR DESCRIPTION
**Pull request by rastersize**
### Goals :soccer:
- Align `request(_:)` with the other methods.

### Implementation Details :construction:
All the other request, download, upload and so on methods are annotated with `@discardableResult`. This changes makes sure that method can be used for fire-and-forget calls.

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! Cheers! 🍻

**Comment by jpdutoit** [comment]
Should this be reverted in the latest version? It looks like the request is being released automatically if no response handler is added...

**Comment by jshier** [comment]
We probably should, but it would need a major version revision. We'll have to see how the next version's APIs shake out and reevaluate.

**Comment by jpdutoit** [comment]
Ok. In our case this caused a bunch of problems when our fire-and-forget API calls stopped firing after updating Alamofire.

**Comment by jshier** [comment]
To be clear, that behavioral change is intentional, as `Request`s no longer start until a response handler has been added or `resume()` has been called. That's true whether or not the instance is retained.

**Comment by jpdutoit** [comment]
Thanks for the clarification. I must have missed it in the release notes

**Pull request merged**
