### PR TITLE
Add privacy manifest

### PR DESCRIPTION
**Pull request by kdvmgn**
### Issue Link :link:
[Apple's update to their API policy - Required Reason](https://github.com/Alamofire/Alamofire/issues/3761)

### Goals :soccer:
To comply with Apple's new privacy policies every app and third-party SDK should include a Privacy manifest in case if they access APIs which potentially can be used for fingerprinting. All use cases of such API require explicit reasons declaration.
Alamofire accesses `systemUptime` property which is included in a required reasons API.

### Implementation Details :construction:
- Added a PrivacyInfo.xcprivacy file. The file requires all four fields to be included:
  - SDK does not use tracking;
  - Tracking domains array is empty. It can be empty as long as tracking is false;
  - SDK does not collect any data. NSPrivacyCollectedDataTypes is empty;
  - SDK uses `systemUptime`, Reason: [35F9.1: Measure time on-device, per documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394)
- Updated package.swift file to include the privacy manifest to the SP.

### Testing Details :mag:
Not applicable

### CODE REVIEW

**Comment by jshier** [comment]
Thanks a lot for this! Apple actually reached out to Alamofire (as they did with many other popular dependencies) and I asked what the proper handling was for SPM (and CocoaPods, though I don't expect anything there) and I haven't heard back. This is what I expected, but for Alamofire to truly ship this we need to support it through CocoaPods and Carthage as well (Carthage is probably just integrating it into our Xcode project). Any chance you can look at those as well?

**Comment by jshier** [comment]
Personally, I'm also skeptical that Apple will actually make this a full requirement, so I'd probably wait to merge it for a while anyway.

**Comment by kdvmgn** [comment]
@jshier I totally understand. We never know for sure, but it could help us to be prepared. I'm fine with put it on hold for now.

**Comment by ag-drivequant** [comment]
Hello

As you know, Apple listed Alamofire on [the list of SDKs that require a privacy manifest](https://developer.apple.com/support/third-party-SDK-requirements/)

Do you plan to the privacy manifest for older major version, or just for Alamofire 5.X ?

I am asking the question because I am still using Alamofire 4.9.1 on one of my projects

**Comment by wlxo0401** [comment]
@kdvmgn 

I don't think there's anything about podspec.

**Comment by kalsariyarahul** [comment]
> Personally, I'm also skeptical that Apple will actually make this a full requirement, so I'd probably wait to merge it for a while anyway.

Do you know when we can expect the app privacy policy to be added?

**Comment by wlxo0401** [comment]
@all

I discovered a new fact while testing. Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Personal Information Nutrition Label Type', the library name is displayed in the personal information protection report. 

Many libraries have updated PrivacyInfo without adding anything from Privacy Nutrition Label Types.

Does anyone know about this? Is "Privacy Nutrition Label Types" a must-have item?

**Comment by FONickReichard** [comment]
Hello, is there a reason thats preventing this PR from getting merged?

**Comment by JeanAzzopardi** [comment]
@jshier - Seeing that Spring 2024 is soon upon us and Apple listed Alamofire specifically as needing a privacy manifest, is there an issue preventing the PR from being merged?

> Starting in spring 2024, in order to upload your new app or app update to App Store Connect, you’ll be required to include an approved reason in the app’s privacy manifest which accurately reflects how your app uses the API.

**Comment by TrabelsiAchraf** [comment]
Hi, I have a legacy that use Alamofire 4.5 and when I want to update to the last version that support Manifest Privacy file I have a code broken and It will take a lot of time to updated, is it possible to add this Manifest Privacy file to 4.5 version ?

**Comment by jshier** [comment]
It's unclear whether Apple will require existing apps with old dependencies to add privacy manifests for those dependencies. The plain language of their documentation seems to imply so, but my discussions with Apple seem to imply that only the addition of the dependency requires a manifest. In either case, there will be no updates to Alamofire 4, both because it's been four years since 5 was released, and because it doesn't use the restricted API that 5 does. 

If anyone does update an existing app and get the warnings, let me know so I can reach out to Apple again for clarification.

**Comment by TrabelsiAchraf** [comment]
Okay thank you @jshier for the explanation.

**Comment by WGMB** [comment]
Hi, please create new release version with the latest changes and a Cocoapods release as well.

**Pull request merged**
